In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
df.shape

(150, 6)

In [ ]:
df.columns

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [ ]:
df.columns=[1,2,3,4,5,6]
df.columns

Int64Index([1, 2, 3, 4, 5, 6], dtype='int64')

In [ ]:
print(df[6].value_counts())
x=df.iloc[:,1:5]
y=df.iloc[:,5]
print('x')
print(x)
print('y')
print(y)

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: 6, dtype: int64
x
       2    3    4    5
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
y
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 6, Length: 150, dtype: object


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)
print('x')
print(x_train)
print('y')
print(y_train)

x
       2    3    4    5
61   5.9  3.0  4.2  1.5
92   5.8  2.6  4.0  1.2
112  6.8  3.0  5.5  2.1
2    4.7  3.2  1.3  0.2
141  6.9  3.1  5.1  2.3
..   ...  ...  ...  ...
9    4.9  3.1  1.5  0.1
103  6.3  2.9  5.6  1.8
67   5.8  2.7  4.1  1.0
117  7.7  3.8  6.7  2.2
47   4.6  3.2  1.4  0.2

[112 rows x 4 columns]
y
61     Iris-versicolor
92     Iris-versicolor
112     Iris-virginica
2          Iris-setosa
141     Iris-virginica
            ...       
9          Iris-setosa
103     Iris-virginica
67     Iris-versicolor
117     Iris-virginica
47         Iris-setosa
Name: 6, Length: 112, dtype: object


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kn=KNeighborsClassifier(n_neighbors=1)
kn.fit(x_train,y_train)
y_predict=kn.predict(x_test)

In [ ]:
print(y_test)
print("-------------------------------------")
print(y_predict)

114     Iris-virginica
62     Iris-versicolor
33         Iris-setosa
107     Iris-virginica
7          Iris-setosa
100     Iris-virginica
40         Iris-setosa
86     Iris-versicolor
76     Iris-versicolor
71     Iris-versicolor
134     Iris-virginica
51     Iris-versicolor
73     Iris-versicolor
54     Iris-versicolor
63     Iris-versicolor
37         Iris-setosa
78     Iris-versicolor
90     Iris-versicolor
45         Iris-setosa
16         Iris-setosa
121     Iris-virginica
66     Iris-versicolor
24         Iris-setosa
8          Iris-setosa
126     Iris-virginica
22         Iris-setosa
44         Iris-setosa
97     Iris-versicolor
93     Iris-versicolor
26         Iris-setosa
137     Iris-virginica
84     Iris-versicolor
27         Iris-setosa
127     Iris-virginica
132     Iris-virginica
59     Iris-versicolor
18         Iris-setosa
83     Iris-versicolor
Name: 6, dtype: object
-------------------------------------
['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_predict))
acc=accuracy_score(y_test,y_predict)*100
print(acc)

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
97.36842105263158


In [ ]:
xnew=np.array([[1,4,2,3]])
kn.predict(xnew)

array(['Iris-setosa'], dtype=object)

In [ ]:
xnew=np.array([[2.3,2.9,5.0,1.9]])
kn.predict(xnew)

array(['Iris-virginica'], dtype=object)